### ISSUE TITLE
Ubuntu 24.04 Error starting container: UnboundLocalError: local variable 'config' referenced before assignment

### ISSUE THREAD

**Issue by adicorrales** [snowzach/doods2#109]
I just migrate my server to ubuntu 24.04 and I'm unable to start doods2 container with this error:

```
mapping values are not allowed here
  in "config.yaml", line 3, column 7
Traceback (most recent call last):
  File "main.py", line 91, in <module>
    main()
  File "main.py", line 54, in main
    if isinstance(config.doods.boxes.boxColor, str):
UnboundLocalError: local variable 'config' referenced before assignment
```

The exact same compose file and config.yaml work fine on ubuntu 22.04. Even exporting a working image from 22.04 to 24.04 the container is unable to start.

Of 4 containers, this is the only one that is not working on the new system.

**Comment by adicorrales** [comment]
Never mind... After some updates, it is working now. No idea what were wrong.

**Comment by adicorrales** [comment]
Never mind. After some updates, it is working again. Don't know what were wrong.
