### ISSUE TITLE
An error is displayed when trying to use the Yolov8 EdgeTPU model

### ISSUE THREAD

**Issue by pantan-cymk** [snowzach/doods2#117]
I am using it via the doods2 add-on of HomeAssistant on Raspberrypi. EdgeTPU uses ssdlite_mobiledet_coco_qat_postprocess_edgetpu.tflite.

The Yolov8 tfile corresponding to the EdgeTPU for which the error was output can be found on the following site.
Exported Yolov8 EdgeTPU model
https://github.com/jveitchmichaelis/edgetpu-yolo/tree/main

I thought it might be because of the model, so I exported it myself using the following site, but I got the same error.
https://docs.ultralytics.com/integrations/edge-tpu/

It seems to be an error in the set_tensor part of doods2 tfile.py, but is there something wrong with my specification?

Error contents are as follows:
```
024-08-14 21:36:17,556 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.8/dist-packages/prometheus_fastapi_instrumentator/middleware.py", line 169, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/prometheus_fastapi_instrumentator/middleware.py", line 167, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/opt/doods/api.py", line 47, in detect
    detect_response = self.doods.detect(detect_request)
  File "/opt/doods/doods.py", line 139, in detect
    ret = detector.detect(image)
  File "/opt/doods/detectors/tflite.py", line 91, in detect
    interpreter.set_tensor(self.input_details[0]['index'], input_data)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/interpreter.py", line 705, in set_tensor
    self._interpreter.SetTensor(tensor_index, value)
ValueError: Cannot set tensor: Got value of type UINT8 but expected type INT8 for input 0, name: serving_default_images:0 
```

Settings below:
```
doods.detectors
- name: default
  type: tflite
  modelFile: /share/models/yolov8s_full_integer_quant_edgetpu_192.tflite
  labelFile: /share/models/coco_labels_edgetpu.txt
  hwAccel: true
```

**Comment by ecdlguy** [comment]
Hi, I'd be also interested how this can be done. Did you mange to get it work?

**Comment by pantan-cymk** [comment]
It's still not working.

Actually, I discovered another problem.

To solve this problem, I rebuilt the Doods2 docker image for the first time in a year, and now it causes a segmentation fault when loading EdgeTPU.

Now it's being processed by the CPU 😅

When I have time, I'm thinking of updating libedgetpu and testing it.

I guess I need to use the libedgetpu from the following site...

https://github.com/feranick/libedgetpu
