### ISSUE TITLE
Doods2 in Home Assistant

### ISSUE THREAD

**Issue by FnRsre** [snowzach/doods2#121]
I'm trying to run Doods2 from the Home Assistant Addon Store with default settings but it crashes and gives the following in logs. I'm running Home Assistant on a Raspberry Pi 4. Any help would be greatly appreciated.

Traceback (most recent call last):
  File "/opt/doods/main.py", line 5, in <module>
    from api import API
  File "/opt/doods/api.py", line 2, in <module>
    import odrpc
  File "/opt/doods/odrpc.py", line 3, in <module>
    from pydantic.dataclasses import dataclass
  File "/usr/local/lib/python3.11/dist-packages/pydantic/__init__.py", line 2, in <module>
    from . import dataclasses
  File "/usr/local/lib/python3.11/dist-packages/pydantic/dataclasses.py", line 48, in <module>
    from typing_extensions import dataclass_transform
ImportError: cannot import name 'dataclass_transform' from 'typing_extensions' (/usr/local/lib/python3.11/dist-packages/typing_extensions.py)
Traceback (most recent call last):
  File "/opt/doods/main.py", line 5, in <module>
    from api import API
  File "/opt/doods/api.py", line 2, in <module>
    import odrpc
  File "/opt/doods/odrpc.py", line 3, in <module>
    from pydantic.dataclasses import dataclass
  File "/usr/local/lib/python3.11/dist-packages/pydantic/__init__.py", line 2, in <module>
    from . import dataclasses
  File "/usr/local/lib/python3.11/dist-packages/pydantic/dataclasses.py", line 48, in <module>
    from typing_extensions import dataclass_transform
ImportError: cannot import name 'dataclass_transform' from 'typing_extensions' (/usr/local/lib/python3.11/dist-packages/typing_extensions.py)
Traceback (most recent call last):
  File "/opt/doods/main.py", line 5, in <module>
    from api import API
  File "/opt/doods/api.py", line 2, in <module>
    import odrpc
  File "/opt/doods/odrpc.py", line 3, in <module>
    from pydantic.dataclasses import dataclass
  File "/usr/local/lib/python3.11/dist-packages/pydantic/__init__.py", line 2, in <module>
    from . import dataclasses
  File "/usr/local/lib/python3.11/dist-packages/pydantic/dataclasses.py", line 48, in <module>
    from typing_extensions import dataclass_transform
ImportError: cannot import name 'dataclass_transform' from 'typing_extensions' (/usr/local/lib/python3.11/dist-packages/typing_extensions.py)

**Comment by GrouxCL** [comment]
I have the same problem on my Home Assistant with DOODS2 installed as an add-on on a Pi 4 also. I tried to uninstall it and then reinstall it but it doesn’t change anything... Anyone found a way to fix this?
