### ISSUE TITLE
Error installing on armv7l-based machine

### ISSUE THREAD

**Issue by duffyd** [snowzach/doods2#5]
After running (**latest** tag returns same error):

> docker run -it -p 8080:8080 snowzach/doods2:armv7l

I get:

> Unable to find image 'snowzach/doods2:armv7l' locally
armv7l: Pulling from snowzach/doods2
Digest: sha256:8393763dc3067984fd9f35e71571b9fadf14b515b2577cbd0da4358fc3f5268c
Status: Downloaded newer image for snowzach/doods2:armv7l
/usr/local/lib/python3.8/dist-packages/tensorflow_io/python/ops/__init__.py:98: UserWarning: unable to load libtensorflow_io_plugins.so: unable to open file: libtensorflow_io_plugins.so, from paths: ['/usr/local/lib/python3.8/dist-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so']
caused by: ["[Errno 2] The file to load file system plugin from does not exist.: '/usr/local/lib/python3.8/dist-packages/tensorflow_io/python/ops/libtensorflow_io_plugins.so'"]
  warnings.warn(f"unable to load libtensorflow_io_plugins.so: {e}")
/usr/local/lib/python3.8/dist-packages/tensorflow_io/python/ops/__init__.py:104: UserWarning: file system plugins are not loaded: unable to open file: libtensorflow_io.so, from paths: ['/usr/local/lib/python3.8/dist-packages/tensorflow_io/python/ops/libtensorflow_io.so']
caused by: ['/usr/local/lib/python3.8/dist-packages/tensorflow_io/python/ops/libtensorflow_io.so: cannot open shared object file: No such file or directory']
  warnings.warn(f"file system plugins are not loaded: {e}")
Traceback (most recent call last):
  File "main.py", line 35, in <module>
    main()
  File "main.py", line 30, in main
    api.run()
  File "/opt/doods/api.py", line 83, in run
    uvicorn.run(self.api, host=self.config.host, port=self.config.port) 
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/main.py", line 452, in run
    server.run()
  File "/usr/local/lib/python3.8/dist-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/runners.py", line 39, in run
    loop = events.new_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 758, in new_event_loop
    return get_event_loop_policy().new_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 656, in new_event_loop
    return self._loop_factory()
  File "/usr/lib/python3.8/asyncio/unix_events.py", line 54, in __init__
    super().__init__(selector)
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 55, in __init__
    super().__init__()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 397, in __init__
    self._clock_resolution = time.get_clock_info('monotonic').resolution
PermissionError: [Errno 1] Operation not permitted
Exception ignored in: <function BaseEventLoop.__del__ at 0x767080b8>
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/base_events.py", line 654, in __del__
    _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 416, in __repr__
    f'<{self.__class__.__name__} running={self.is_running()} '
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1878, in get_debug
    return self._debug
AttributeError: '_UnixSelectorEventLoop' object has no attribute '_debug'
sys:1: RuntimeWarning: coroutine 'Server.serve' was never awaited

**Comment by duffyd** [comment]
Not sure if this may help, but I found this [webpage](https://www.bitsy.ai/3-ways-to-install-tensorflow-on-raspberry-pi/)

**Comment by snowzach** [comment]
Yeah, this is a bug in Raspbian+Docker... You need to upgrade a library. This should fix it: https://docs.linuxserver.io/faq

**Comment by snowzach** [comment]
Going to close this, reopen if you still have issues.

**Comment by duffyd** [comment]
It works!!! Thanks!!
