### ISSUE TITLE
Doods2 still doesn't work after update (See latest #52)

### ISSUE THREAD

**Issue by Idefix0496** [snowzach/doods2#53]
Hey I've still got the same Problem. Using a Model which was trained on a recent yolov5 Docker Image I'm getting the following Error Messages:

2022-09-10 17:02:25,639 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
result = await app(self.scope, self.receive, self.send)
File "/usr/local/lib/python3.8/dist-packages/uvicorn/middleware/proxy_headers.py", line 75, in call
return await self.app(scope, receive, send)
File "/usr/local/lib/python3.8/dist-packages/fastapi/applications.py", line 208, in call
await super().call(scope, receive, send)
File "/usr/local/lib/python3.8/dist-packages/starlette/applications.py", line 112, in call
await self.middleware_stack(scope, receive, send)
File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/errors.py", line 159, in call
await self.app(scope, receive, _send)
File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/base.py", line 57, in call
task_group.cancel_scope.cancel()
File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 572, in aexit
raise ExceptionGroup(exceptions)
anyio._backends._asyncio.ExceptionGroup: 2 exceptions were raised in the task group:
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/base.py", line 55, in call
response = await self.dispatch_func(request, call_next)
File "/usr/local/lib/python3.8/dist-packages/prometheus_fastapi_instrumentator/instrumentation.py", line 172, in dispatch_middleware
raise e from None
File "/usr/local/lib/python3.8/dist-packages/prometheus_fastapi_instrumentator/instrumentation.py", line 169, in dispatch_middleware
response = await call_next(request)
File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/base.py", line 37, in call_next
raise RuntimeError("No response returned.")
RuntimeError: No response returned.
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/starlette/middleware/base.py", line 30, in coro
await self.app(scope, request.receive, send_stream.send)
File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 82, in call
raise exc
File "/usr/local/lib/python3.8/dist-packages/starlette/exceptions.py", line 71, in call
await self.app(scope, receive, sender)
File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 656, in call
await route.handle(scope, receive, send)
File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 259, in handle
await self.app(scope, receive, send)
File "/usr/local/lib/python3.8/dist-packages/starlette/routing.py", line 61, in app
response = await func(request)
File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 234, in app
response_data = await serialize_response(
File "/usr/local/lib/python3.8/dist-packages/fastapi/routing.py", line 137, in serialize_response
raise ValidationError(errors, field.type_)
pydantic.error_wrappers.ValidationError: 1 validation error for DetectorsResponse
response -> detectors -> 0 -> labels
value is not a valid list (type=type_error.list)

I've already raised an Issue on the Yolov5 github Page https://github.com/ultralytics/yolov5/issues/9360
but it seems that there is still an issue on the doods side. In the github issue we discussed a recent change in the class names.
So maybe that's the Problem ?

**Comment by Idefix0496** [comment]
Is there really nobody else with the same issue? At that point the whole thing is pretty unusable.

**Comment by ChienTingLu** [comment]
I am encountering the same problem.
But I just set this up today, so I'm not sure if I did something wrong.

**Comment by snowzach** [comment]
@Idefix0496 your issue is that the labels on your model do not appear to be a list nor a dict like DOODS expects. The only real way for me to fix this is to get a copy of your model and try to figure out what type it is... 

@ChienTingLu your installation actually appears to be working fine... I see that it completes a couple detections in the log there and dectects a person. It might be some issue in reading the feed from your camera... but otherwise it looks okay.

**Comment by Idefix0496** [comment]
Hey thank's for your answer. I've just tried it again with a freshly trained Coco128 Model (newest Docker Container from yolov5).
The same fault occured again. This is the training command I used:

**python -m torch.distributed.launch --nproc_per_node 2 train.py --batch-size 12 --workers 10 --epochs 5 --img 640 --data coco128.yaml --weights yolov5s.pt**

And here is the trained Model with the imminent Fault:
[best.zip](https://github.com/snowzach/doods2/files/9677181/best.zip)

I would really appreciate it if you could take a look.

**Comment by snowzach** [comment]
Okay, I think I figured it out. The Yolo support library was out of date. Try pulling the latest image and see if that works.

**Comment by Idefix0496** [comment]
Hey thank's for your effort's. It's working fine now. I've tested it with a new trained Model which wasn't working before.
The Webview is also working again without the Error showing up.
