### ISSUE TITLE
undefined symbol: cublasLtGetStatusString, version libcublasLt.so.11

### ISSUE THREAD

**Issue by scottgrobinson** [snowzach/doods2#71]
Run up the latest docker image and getting the following error

```
doods_1  | Traceback (most recent call last):
doods_1  |   File "main.py", line 8, in <module>
doods_1  |     from doods import Doods
doods_1  |   File "/opt/doods/doods.py", line 20, in <module>
doods_1  |     from detectors.pytorch import PyTorch
doods_1  |   File "/opt/doods/detectors/pytorch.py", line 7, in <module>
doods_1  |     import torch
doods_1  |   File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 191, in <module>
doods_1  |     _load_global_deps()
doods_1  |   File "/usr/local/lib/python3.8/dist-packages/torch/__init__.py", line 153, in _load_global_deps
doods_1  |     ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
doods_1  |   File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
doods_1  |     self._handle = _dlopen(self._name, mode)
doods_1  | OSError: /usr/local/lib/python3.8/dist-packages/torch/lib/../../nvidia/cublas/lib/libcublas.so.11: undefined symbol: cublasLtGetStatusString, version libcublasLt.so.11
```

Docker compose file:
```
version: '3.2'

services:
  doods:
    image: snowzach/doods2:amd64-gpu
    ports:
      - "8088:8080"
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```

Output of nvidia-smi/nvcc
```
console@DellServer:~/docker/doods$ nvidia-smi
Mon Dec 19 11:23:18 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.216.04   Driver Version: 450.216.04   CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro P600         Off  | 00000000:01:00.0 Off |                  N/A |
| 27%   42C    P0    N/A /  N/A |      0MiB /  2000MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

console@DellServer:~/docker/doods$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0

```

**Comment by snowzach** [comment]
Hrmm... looks like some sort of incompatibility with the base OS and the image CUDA version...

**Comment by darknicht66** [comment]
The issue is that pytorch 1.13 automatically installs nvidia_cublas_cu11, nvidia_cuda_nvrtc_cu11, nvidia_cuda_runtime_cu11 and nvidia_cudnn_cu11. This conflicts with the nvidia_toolkit versions passed through from the host installation. Either revert to using pytorch 1.12 in the image or perform a 'pip uninstall nvidia_cublas_cu11' in the docker container after the pytorch 1.13 installation.

**Comment by snowzach** [comment]
Consider this solved. Thanks.

**Comment by scottgrobinson** [comment]
Spooky timing - I only got around to testing this about four hours before you commented and closed, but the above library path fix did solve my issue. Thank you - Much appreciated.
